services:
  # Apply memory/CPU pressure limits to each node container
  node1:
    mem_limit: 128m
    cpus: "0.5"

  node2:
    mem_limit: 128m
    cpus: "0.5"

  node3:
    mem_limit: 128m
    cpus: "0.5"

  node4:
    mem_limit: 128m
    cpus: "0.5"

  node5:
    mem_limit: 128m
    cpus: "0.5"

  chaos-killer:
    image: docker:24.0-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      /bin/sh -c 'set -e; echo "Chaos-killer started"; while true; do TARGET=$(docker ps --format "{{.Names}}" | grep -E "node[0-9]+$" | shuf -n 1); echo "[KILLER] Restarting $TARGET"; docker restart $TARGET; INTERVAL=$(shuf -i 10-40 -n 1); echo "[KILLER] sleeping $INTERVAL s"; sleep $INTERVAL; done'
    networks:
      - vaultnet
    restart: unless-stopped
