global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "vault-nodes"
    static_configs:
      - targets:
          ["node1:8080", "node2:8080", "node3:8080", "node4:8080", "node5:8080"]
    metrics_path: "/metrics"
