{
 "title": "DKG Metrics Dashboard",
 "tags": [
  "dkg",
  "threshold",
  "cryptography"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source Node",
    "query": "label_values(dkg_round1_packages_received, source)"
   }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total DKG Starts by Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(peer_from) (dkg_start_dkg_initiated)",
     "legendFormat": "{{peer_from}} - Total DKG Starts"
    }
   ]
  },
  {
   "title": "Total Round1 Packages Received by Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (dkg_round1_packages_received)",
     "legendFormat": "{{source}} - Total Round1"
    }
   ]
  },
  {
   "title": "Total Round2 Packages Received by Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (source) (dkg_round2_packages_received)",
     "legendFormat": "{{source}} - Total Round2"
    }
   ]
  },
  { "title": "Round 1 Node Sent Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Node 5 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "dkg_round1_packages_received{source=\"node_5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 1 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "dkg_round1_packages_received{source=\"node_1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 2 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
   "targets": [
    {
     "expr": "dkg_round1_packages_received{source=\"node_2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 3 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "dkg_round1_packages_received{source=\"node_3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 4 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "dkg_round1_packages_received{source=\"node_4\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Round 2 Node Sent Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true
  },
  {
   "title": "Node 1 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "dkg_round2_packages_received{source=\"node_1\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 2 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 33 },
   "targets": [
    {
     "expr": "dkg_round2_packages_received{source=\"node_2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 3 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "dkg_round2_packages_received{source=\"node_3\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 4 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "dkg_round1_packages_received{source=\"node_4\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node 5 Sent Packages",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "dkg_round2_packages_received{source=\"node_5\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}