[package]
name = "consensus_timer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["time", "rt"] }
tracing = { workspace = true }
types = { path = "../types" }

