[package]
name = "cli"
description = "Command-line interface for the Threshold network"
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
tokio.workspace = true
libp2p.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
clap.workspace = true
bs58.workspace = true
directories.workspace = true
argon2.workspace = true
aes-gcm.workspace = true
base64.workspace = true
rpassword.workspace = true
dotenvy.workspace = true
derive_more.workspace = true
tonic.workspace = true

node = { path = "../../crates/node" }
types = { path = "../../crates/types" }

[dev-dependencies]
tempfile.workspace = true
assert_matches.workspace = true

[lints]
workspace = true
