[package]
name = "utxo-spend"
description = "Utxo spend service for the Threshold network"
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[dependencies]
bitcoin.workspace = true
tokio.workspace = true
bip39.workspace = true
tonic.workspace = true
esplora-client.workspace = true
hex.workspace = true
dotenvy.workspace = true

node = { path = "../../crates/node" }
protocol = { path = "../../crates/protocol" }
oracle = { path = "../../crates/oracle" }

[dev-dependencies]
tempfile.workspace = true
assert_matches.workspace = true

[lints]
workspace = true